#!/bin/bash

echo "🧪 Quick Messaging Test"
echo "======================"
echo ""
echo "Testing messaging system between agent and client..."
echo ""
echo "📋 Prerequisites:"
echo "   1. Login as agent"
echo "   2. Go to Messages"
echo "   3. Send a test message"
echo "   4. Check browser console for:"
echo "      ✅ 'Message sent to Firebase'"
echo "      ✅ 'Message archived to PostgreSQL'"
echo ""
echo "📋 Next:"
echo "   1. Open new browser (Incognito)"
echo "   2. Login as client"
echo "   3. Go to Messages"
echo "   4. Verify message appears in real-time"
echo ""
echo "✅ Check Firebase Console:"
echo "   → https://console.firebase.google.com"
echo "   → Your Project → Realtime Database"
echo "   → Check: chats/{caseId}/messages"
echo ""
echo "✅ Check PostgreSQL:"
echo "   → Your Database → chat_messages table"
echo "   → Verify message is archived"
